name: release

on:
  push:
    branches:
      - main

env:
  CGO_CFLAGS: '-O3'
  CGO_CXXFLAGS: '-O3'

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      GOFLAGS: ${{ steps.goflags.outputs.GOFLAGS }}
      VERSION: ${{ steps.goflags.outputs.VERSION }}
      vendorsha: ${{ steps.changes.outputs.vendorsha }}
    steps:
      - uses: actions/checkout@v4
      - name: Set environment
        id: goflags
        run: |
          echo GOFLAGS="'-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=${GITHUB_REF_NAME#v}\" \"-X=github.com/ollama/ollama/server.mode=release\"'" | tee -a $GITHUB_OUTPUT
          echo VERSION="${GITHUB_REF_NAME#v}" | tee -a $GITHUB_OUTPUT
          echo vendorsha=$(make -f Makefile.sync print-base) | tee -a $GITHUB_OUTPUT

  # Build each Docker variant (OS, arch, and flavor) separately. Using QEMU is unreliable and slower.
  docker-build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: arm64
            build-args: |
              CGO_CFLAGS
              CGO_CXXFLAGS
              GOFLAGS
          - os: linux
            arch: amd64
            build-args: |
              CGO_CFLAGS
              CGO_CXXFLAGS
              GOFLAGS
          - os: linux
            arch: amd64
            suffix: '-rocm'
            build-args: |
              CGO_CFLAGS
              CGO_CXXFLAGS
              GOFLAGS
              FLAVOR=rocm
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs: setup-environment
    env:
      GOFLAGS: ${{ needs.setup-environment.outputs.GOFLAGS }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      # - uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          build-args: ${{ matrix.build-args }}
          push: false
          # outputs: type=image,name=${{ vars.DOCKER_REPO }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Rotate cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # # Merge Docker images for the same flavor into a single multi-arch manifest
  # docker-merge-push:
  #   strategy:
  #     matrix:
  #       suffix: ['', '-rocm']
  #   runs-on: ubuntu-latest
  #   environment: release
  #   needs: [docker-build-push]
  #   steps:
  #     - uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKER_USER }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #     - id: metadata
  #       uses: docker/metadata-action@v4
  #       with:
  #         flavor: |
  #           latest=false
  #           suffix=${{ matrix.suffix }}
  #         images: |
  #           ${{ vars.DOCKER_REPO }}
  #         tags: |
  #           type=ref,enable=true,priority=600,prefix=pr-,event=pr
  #           type=semver,pattern={{version}}
  #     - uses: actions/download-artifact@v4
  #       with:
  #         pattern: digest-*
  #         path: ${{ runner.temp }}
  #         merge-multiple: true
  #     - run: |
  #         docker buildx imagetools create $(echo '${{ steps.metadata.outputs.json }}' | jq -cr '.tags | map("-t", .) | join(" ")') $(cat *-${{ matrix.suffix }}.txt | xargs printf '${{ vars.DOCKER_REPO }}@%s ')
  #         docker buildx imagetools inspect ${{ vars.DOCKER_REPO }}:${{ steps.metadata.outputs.version }}
  #       working-directory: ${{ runner.temp }}

  # # Build Linux binaries and tarballs
  # linux-build:
  #   strategy:
  #     matrix:
  #       include:
  #         - os: linux
  #           arch: amd64
  #           target: archive
  #         - os: linux
  #           arch: amd64
  #           target: rocm
  #         - os: linux
  #           arch: arm64
  #           target: archive
  #   runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
  #   environment: release
  #   needs: setup-environment
  #   env:
  #     GOFLAGS: ${{ needs.setup-environment.outputs.GOFLAGS }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         platforms: ${{ matrix.os }}/${{ matrix.arch }}
  #         target: ${{ matrix.target }}
  #         build-args: |
  #           GOFLAGS=${{ env.GOFLAGS }}
  #           CGO_CFLAGS=${{ env.CGO_CFLAGS }}
  #           CGO_CXXFLAGS=${{ env.CGO_CXXFLAGS }}
  #         outputs: type=local,dest=dist/${{ matrix.os }}-${{ matrix.arch }}
  #         cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}:latest
  #         cache-to: type=inline
  #     - name: Deduplicate CUDA libraries
  #       run: |
  #         ./scripts/deduplicate_cuda_libs.sh dist/${{ matrix.os }}-${{ matrix.arch }}
  #     - run: |
  #         for COMPONENT in bin/* lib/ollama/*; do
  #           case "$COMPONENT" in
  #             bin/ollama*)               echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/*.so*)          echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/cuda_v*)        echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/vulkan*)        echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/mlx*)           echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/include*)       echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}.tar.in ;;
  #             lib/ollama/cuda_jetpack5)  echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}-jetpack5.tar.in ;;
  #             lib/ollama/cuda_jetpack6)  echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}-jetpack6.tar.in ;;
  #             lib/ollama/rocm)           echo $COMPONENT >>ollama-${{ matrix.os }}-${{ matrix.arch }}-rocm.tar.in ;;
  #           esac
  #         done
  #       working-directory: dist/${{ matrix.os }}-${{ matrix.arch }}
  #     - run: |
  #         for ARCHIVE in dist/${{ matrix.os }}-${{ matrix.arch }}/*.tar.in; do
  #           tar c -C dist/${{ matrix.os }}-${{ matrix.arch }} -T $ARCHIVE --owner 0 --group 0 | zstd --ultra -22 -T0 >$(basename ${ARCHIVE//.*/}.tar.zst);
  #         done
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: bundles-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.target }}
  #         path: |
  #           *.tar.zst

  # # Final release process
  # release:
  #   runs-on: ubuntu-latest
  #   environment: release
  #   needs: [linux-build]
  #   permissions:
  #     contents: write
  #   env:
  #     GH_TOKEN: ${{ github.token }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         pattern: bundles-*
  #         path: dist
  #         merge-multiple: true
  #     - name: Generate checksum file
  #       run: find . -type f -not -name 'sha256sum.txt' | xargs sha256sum | tee sha256sum.txt
  #       working-directory: dist
  #     - name: Create or update Release for tag
  #       run: |
  #         gh release create ${GITHUB_REF_NAME} \
  #           --title ${GITHUB_REF_NAME#v} \
  #           --draft \
  #           --generate-notes \
  #           --prerelease
  #     - name: Upload release artifacts
  #       run: |
  #         for payload in dist/*.txt dist/*.zip dist/*.tgz dist/*.tar.zst dist/*.sh ; do
  #           gh release upload ${GITHUB_REF_NAME} $payload --clobber
  #         done
